:PROPERTIES:
:ID:       db23925b-0c15-4611-99b3-8198ff344c82
:END:
#+title: mech 6040 report
#+filetags: :proj:masc:

* Formatting
- 10-15 page limit
- title page
- 8-12 body pages
- 1 ref page

* Title Page
- Course
- Project Title
- Figure
- Student Name
- Date & Signature?

* Main Body
- walk reader through
- dos and donts - present within each component blurb
- problems and solutions - present wihtin each component blurb

** Formatting
- 10-13 pages
- 1000-2000 word
- 10-12 FIgures

** How to

*** Assembly
- great place for exploded diagram idenifying components
- lego axel lengths!
  
**** Rotating Assembly
- assemble one flap wheel ot lego shaft
- assemble second flap wheel and ensure both flap wheel holes align by temprarily mating both components
- remove one flap wheel, noting its orientation on the lego axis
- insert large spacer between both flap wheels and replace second flap wheel
- insert individual flaps by exploiting flap compliance, flaps shoudl snap into place with low applied force
- assemble the 11mm spacer outside the flap wheel assembly, followed by the worm folloer gear
- assemble a 1mm spacer on the opposing side of the flap wheel assembly
- to complete the rotating assembly, assemble a 2mm spacer outside the worm follower gear

**** Shell
- assemble the round bevel gear mount and worm gear mounts by pressing into the right shell half
- where are they pressed in!
- assemble the worm, straddled by two 1mm spacers between both worm mounts and peirce with a lego axle
- stack the remaining bevel gear, 1mm spacer, c-bevel mount and handle, ensuring that the c-bevel mount ends curl towards the bevel gear
- peice the stacked components with a lego axle
- press the bevel gear assembly into the holes above and below the round bevel gear mount
- assemble the 4mm spacer and one bevel gear respectively to the worm axle end nearest the bevel gear mount, ensuring bevel gear meshes with other

**** Final
- insert axle end or rotating assembly with worm follower gear into the centre hole in right side shell, careful to mate worm with worm follower gear
- assmeble left shell half to opposing end of rotating assembly shaft
- insert connectors into top and bottom, mating shell halves
- insert top (long) and bottom (short) stops into shell cutouts near top and bottom

** Build Steps
The driving design factors for this split flap display assembly are:
- minimize overall size, whilst maximizing flap display area
- ensure displays can be assembled in a modular array for use as a clock
- smooth operation
- consistent flap actuation

All component faces interfacing with the build plate incoporate a small chamfer to improve finish quality and minimize elephants foot.
  
*** TODO
- reference teds lego axle profile and include drawing
- units from Doman template
- worm video reference
- bevel gear video reference
- notes on how parts were printed? if its important to the design
- reference all components to named item in exploded drawing

*** Fits
Wihtin the following component breakdowns are various references concerning part fits. These references are defined in the following tables [ref] and [ref] for use throughout the report. The offset column in table [ref] indicates the difference in dimensions for interfacing features, such that the hole feature is always larger in size than the mating feature. Similarly in table [ref] the offset column indicates the amount added to the stock LEGO axle profile [ref], in creating LEGO axle hole features. 

Fits for 3D Printed Components
| Fit Type       | Offset [mm] | Description                                                                                                                           |
|----------------+-------------+---------------------------------------------------------------------------------------------------------------------------------------|
| Semi-permanent | 0 0         | Components can be assembled by hand with significant force applied, dissasmbly may require tools and result in permanent deformation  |
| Tight          | 0.05-0.1    | Component can be assembled and dissassembled by hand with moderate force applied                                                      |
| Sliding        | 0.02-0.03   | Components can move freely relative to one another  freely                                                                            |

Fits for LEGO Interfacting Components
| Fit Type     | Offset [mm] | Description                                                         |
|--------------+-------------+---------------------------------------------------------------------|
| Fixed        |    0.05-0.1 | Component does not slide easily on LEGO axle                        |
| Intermediate |     0.1-0.2 | Component does not slide freely, but will slide easily on LEGO axle |
| Sliding      |        0.2+ | Component slides freely on LEGO axle                                |


*** Roating Split Flap Assembly
The key driving factor of the assembly design lies within the rotating split flap assembly. Aspects of both the flaps, and the wheels housing the flaps limit the size and shape of the entire assembly. Critical design elements, challenges and solutions are outlined below.

**** Flaps

***** Design Intent
The vertical to horizontal aspect ratio of the flaps are ultimately driven by the chosen font. Flaps are designed to be easily readable.

***** Design Limitations
The most challenging design contraint for the flap components is thickness. The dominant driver of flap thickness is the relationship with the distance between flap mounting holes. As the flaps are displayed, they must achieve a vertical position, given that the preceeding and proceeding flap are nearly vertical as well, the distance between flap mounting holes must accomodate two flaps oriented vertically and stacked face to face.
The ideal split flap display minizes the central split clearance between vertically displayed flaps. This distance was iteratively optimized by observing flap intererence given various central split clearances.
To ensure smooth actuation, each sucessive flap must be nearly vertical when the upper display flap falls, leaving it exposed. Any additional negative angle relative to the rotating direction will result in a suboptimal viewing angle for the successive flap. The height of the flap relief where the flap wheel is mounted must be minimized to maximize the verticality of each new flap displayed. The optimal geometry has been achived by designing zero clearance between the flap relief and flap moutning wheel when the flaps are oriented vertically.
In minimziang the flap wheel diameter, the flap mounting hole diameters must also be minimized and subsequently, the flap axles dimensions must also be minimized. As the flap thickness limitations are noted above, the height of the flap axles are limited to two extrusion widths, or a single perimiter.

***** Final Design
The flaps are designed to be printed in multiple layers, comprising of black top and bottom layers with display numbers relieved, and a white core to create readiblity and contrast. Each flap side where the relieved number area is minimized is oriented face down on the build plate for idela prinitng. This is critical as the first white layer, or second overall layer, must bridge the area left blank in the initial black layer that forms the number being displayed.

**** Flap Wheels

***** Final Design
There are thirty flaps in the final design as assemblies with  lower flap counts exhibited dissatisfying flap actuation delay, and thirty is a common multiple of both ten and six, allowing the display to be reused in a time keeping array. LEGO axle hole fit is tight, such that they remain in place while assembling flaps.

***** Design Intent
The ideal flap wheel design minimizes flap wheel size, in turn maximizing the flap display area, and allows the flaps to rotate freely wihtin thier respective mounting holes. The flap wheel is critical to achieving smooth and consistent actuation of the split flap display. Designs progressed from thick flaps, and few flap mounting holes, to minimal optimized flap thickness and many flap mounting holes. Increasing the number of flap mounting holes, and subsequently the number of flaps, ensures the delay between the top flap rotating to the bottom flap position, and the next top flap in line reaching a vertical position is decreases, resulting in smoother operation.

***** Design Limitations
The proximity of flap moutning holes to one another is limited by PrusaSlicer. As a minimum of one perimeter must be included  for each component feature. The flap mounting hole size is limited by the flap axle size and flap thickness, as is described above in section [ref - Flaps design limitations]. Rigidity/thicklness anecdote.

**** Central Spacer
  The central spacer performs a critical role in creating smooth flap actuation. The centre spacer sets the distance between the opposing flap mounting wheels, ultimately creating clearance between the flap edges and flap wheels essential to free flap actuation. Five different length spacers were trialed, begginning with the nominal axle distance between flaps, and increasing in 0.1mm increments. The smallest of the spacers was selected for the final design, as flaps could actuate freely without binding, therefore additional flap clearance was not required. The central spacer central hole does not interface with the central LEGA axle, and therefore is designed with a sliding fit.

**** Worm Follower Gear
  The final worm gear design is a thin spur gear with a modulus of one, and thirty teeth. Thirty teeth is chosen to create a 30:1 gear ratio with the worm, resulting in one flap acutation per handle rotation. This simplified increases unit modularity. To prevent the need for a specialized worm follower gear, the thickness of the gear is limited. The gear teeth clearance, defined as the amount symmetrically relived from each tooth, and the mounting clearance, defined as the amount subtracted from the gear pitch diameter are itteratively reduced to achieve an optimal balance between system backlash and required input force. The final worm follower gear is designed with a tight LEGO fit axle hole feature for easy of assembly.

*** Drivetrain
Each drivetrain component is selected and designed to maximize smooth, reliable device actuation. A worm and worm gear drivetrain is selected as a large gear ratio is ideal for a time keeping device. The worm gear drive is coupled with two bevel gears to facilitate easy hand actuation of the split flap display.

**** Worm
A worm with a modulus of one was designed using an online tutorial [ref]. The chosen length of the final design offers sufficient engagement with the worm gear, adding minimal backlahs to the overall drivetrain actuation. A sliding fit offset is applied to the central axial LEGO axle hole feature. No clearances are introduced in the final worm design, as challenging prints limited the itterative design. 

To eliminate the need for support material and improve the surface quality of the worm teeth and axial hole feature, the worm rotational axis is oriented vertically for printing. This orientation introduces build plate adherance issues due to part height, a small brim is added to the base. The worm gear teeth overhang significantly in this orientaiton. Although the teeth overhang did not print failure, it is observed that as teeht are built vertically, eahc tooth tip curls upwards, resulting in an upwards bias of each completed tooth. This did not significantly affect worm performance. The layer height is reduced to facilitate smooth operation of the worm and worm gear drive, and to assist with overhang performance.
  
**** Thrust bearings/spacers
Each drivetrain compoent is seperated by small spacers. Spacers serve multiple functional purposes such as reducing roating friction by mimizing the contact areas of rotaiotnal interfaces, and for precisely aligning components. Spacers are designed with a sliding fit offset for easy assembly. Taller spacers incorporate a brim. Each 3D printed component exhibits both a smooth and rough side, this phenomena allows spacers to also serve as simpl thrust bearings by creating additional smooth rotaionla interfaces within rotating assebmblies.

**** Bevels
The base bevel gear shape is modelled using an instructional video. The base tooth geometry is modified by adding a small chamfer to both circumferential edges of each tooth. The chamfers limit overhangs during print, improve final part quality and facilitate smooth bevel gear engagement. A 24 tooth bevel gear design is chosen for the final componnent, this is the minimum size whithout eliminating the inner bevel gear support, which is essential as is described below in section [ref section about bevel mounting]. The LEGO axle interfacing feature employs an intermediate fit, as one bevel gear is not restricted in the axial direction. 

**** Handle
A simple lego compatible handle is included to facilitate ergonomic device acutation and demonstration. The handle incoporates a LEGO axle feature with am intermediate offset for easy assembly and dissassembly. The handle is fenestrated for asthetic and print time reduction. 

*** Shell
  Shell components are designed for viewing accessibility, sufficient rigidity, and simple assembly/dissasembly. The shell assembly houses both the rotating split flap display assembly and drivetrain components. The shell is predominantly composed of two halves for printing simplicity and easy assembly.

**** Sides

  The shell sides are of simple rectangular design, with mounting features for the central rotating split flap assembly, bevel gear and worm drive. Aside from these mounting features, shell side fenestration is maximized for viewing accessibility, without sacrificng excessive rigidty. Tight fit circular dog-bone cutouts reliveed from protruding features on top and bottom of each side are half of the assembly system, completed by dog bone connectors outlined below in section [ref dog bone connectors]. Shell sides are oriented with top and bottom protrusions extending away from the build plate, such that mechanicsm mounting features are all printed within the XY printing plane. The righ shell half houses mating features both the bevel gear and worm drive mounting components outlined in sections [ref bevel mount] and [ref worm drive mount]. These mating features are modelled with tight fits to both maintain dissembleability and ensure sufficiently consistne device actuation. Small rectagular tight fit cut-outs are provided symetrically in both shell sides for mounting the top and bottom stops.

  Initial shell side designs did not exhibit satisfactory rigidity, allowing for excessive movement of the top flap stop, resulting in inconsistent flap acutation relative to rotaitonla handle motion. Fenestraitons were sucessively reduced until desired rigidity is acheived.  

**** Connectors

  Thje dog-bone connectors mirror the shell side dog-bone cut-outs. Overall connector length is 0.2mm less than the mating feature offsets in the assembled split flap display, effectively preloading the roatating splti flap assembly and creating the resistance required for smooth flap actuation. The connector profile is modelled using a tight fit offset with the mating shell side features, adding rigidity to the overall shell assembly, and holding connectors firmly in place without adhesive.

**** Stops
- initally designed to be adjustable
- measured and installed in shell slots
- difficult to determine geometrically

  The top and bottom stops are an essential and deceptively complex component of the split flap display. Smoothness, consistency and the speed of flap actuation are all functions of the stop components. Different expereiments and adjustable stop assebmlies were employed to determine ideal stop position and thickness. [ref show early stop designs]. The final stop designs are sized using experimental thickness and positional resutls.
  
**** Drivetrain Mounting
Drivetrain mounting components are printed seperately from the shell sides to ensure all axial rotational mounting features are printed wihtin the XY plane, and are not deformed. Oblong hole deformation when printing YZ or XZ planes resulted in rough rotation and inconsistent flap actuation timing. All drivetrain components exhibit tight fit relationships with opposing shell side mounting features, achieving adequate rigidity, while maintaining the ability to dissassmble the drivetrain. List drivetrain components [ref exploded drawing].

** Technical Drawings

** Exploded Diagrams

** Photos

** Performance

