:PROPERTIES:
:ID:       fa48ddb4-12a5-4e81-982c-c41747b1597e
:END:
#+title: bmng5210_project
#+filetags: :final:
* Order List
** Arduino
- https://www.dfrobot.com/product-610.html
  
** Ultrasound Proximity Sensor
- https://www.dfrobot.com/product-2173.html

** RS Converter
- https://www.dfrobot.com/product-1024.html
  
* Make
** Phantoms 
** Sensor Mount
- mount to fan? 32x32 mounting
- need hole/fast sizing
- print w/ support
  
** GCODE
- move
- pull up
- wait
- pull down
- wait
- move
  
*** params
grid size
start x
start y
z hieght
wait time ms

*** preamble
M73 P0 R743
M73 Q0 S748
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.10.1 ; tell printer latest fw version
G90 ; use absolute coordinates
G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

*** pull up
G4 S0 ;Wait for move to finish
M42 S255 P20 ;Trigger
G4 P200 ;Wait for wait time 200ms
M42 S0 P20 ;Untrigger

*** move
- only need to specifiy axis that is being moved!
  G1 X Y Z

* Do
** Test Pull up Pin!
** get data from sensor
- live output may be hlepful
- 12v supply via prusa or plug in or lab supply (temporary but less work)
  
** Arduino Code
*** Sensor Code - done
*** Sensor processing
- remove garbage
- average points
  
** report
** presentation
** compare point cloud to real?
** phantoms
- modelled
- print!

* Resources
** Pull up/Trigger
- https://blog.prusa3d.com/how-to-create-beautiful-3d-print-timelapse-videos_29743/
