':PROPERTIES:
:ID:       87cb0a18-5968-4d04-825c-b3c3d0a4d52f
:END:
#+title: foam 3d printer
#+filetags: :spec:3d:printer:equipment:
* Links
[[id:50d2a39d-8d2c-47fb-af15-d5d8e165dbea][printing space]]
[[id:40c5cd72-9b1a-4ed5-89a4-34802d9e247f][printing ventilation]]

* Summary

** Printing Systems

*** Prusa MK3s+

**** Summary
 Of the 3D printing systems considered, the Prusa MK3S+ is the most suitable choice for the proposed reserach purposes. It is noted that the MK3S+ is also the most expensive printing system by a significanty margin. Employing a direct drive extruder as standard, a capable and upgradable hot end, as well as an outstanding record for end user support and community support content availability. Other notable features of the MK3S+ include a wealth of available peripherals, sensorless homing, a rigid motion system, an inductive levelling sensor and the fastest print speed of the systems considered.
 
**** Pros
- Significant documentation, manufacturer and community support
- Motion system built with solid wheels and high quality bearings, resulting in high accuracy with small scale components
- Fastest print/media throughput capability
  
**** Cons
- High price point
- Possible lead time issues (1-2 weeks minimum)

**** Risks
- TPU filament adheres poorly to the stock coated metal printing beds, instead glass, or garolite are often reccommended. The MK3S+ employes an inductive levelling sensor, meaning that if a non-metallic printing bed of sufficient thickness were used, the inductive sensor would cease to function correctly as it can no longer detect the metal base through the printing base on top. Another potential risk arises in using a non-metallic print bed on top of the metallic print bed, as the inductive type levelling sensor measures the metal bed irregardless. If any non-conformities exist, or the top most printing bed is not secured sufficiently, the measurements of an inductive type levelling sensor are void.

*** Matterhackers Pulse XE

**** Summary
The Matterhackers Pulse is typically reccommended as a cheaper alternative to the Prusa MK3S+. Although the Pulse XE boasts the same high quallity hto end as the MK3S+, many of its other components are lagging in comparison. When considering that the price point is very similar to the MK3S+, it is not reccommended. The Pulse XE slicer is based on the open source CUSA slicer.

**** Cons
- Bowden Tube Style Extruder
- High price point

**** Risks
- Printing with flexible filament using a Bowden Tube extruder is significantly more difficult, less repeatable, and less configurable.

*** Creality Ender 3 S1 

**** Summary
The Creality Ender 3 S1 Pro manages to reach a similar hardware specification as the systems listed above, at a significantly lower price point. In turn Creality offers significantly less end user support, community support is very avaialble, and may require significant user configuration to acheive similar quality results to the other systems. Creality also offers thier own competitive open source slicer which is buld on the popular CUSA engine.

**** Pros
- 32-bit motherboard can calulate more efficient pathing

**** Cons
- User review frequently note uneven bed heating, contributng to adhesion issues in larger components
- Rubber wheels in motion system can reduce print form accuracy

**** Risks
- Extrusion temperatures limited to 300C without upgrading entire extrusion hot end. VarioShore filament notes the minimum extrusion temperature for foaming to occur is 230C, this provides only a small 70C range for experimentation.

** Printing Location

*** Risks
- Ventiliation will be required for printing any of the propsed foaming filaments. Either a printing enclosure with access to ventilation or a highly ventilated room is suggested.

* Comparison Breakdown

** Hot End

| Printer        | Model      | Max. Temp. [C]       | Melting Block Material | Power [W] |
|----------------+------------+----------------------+------------------------+-----------|
| Prusa MK3S+    | E3D V6     | 300 (500 w/ upgrade) | Aluminum Copper        | 30        |
| Ender 3 S1 Pro | Sprite Pro | 300                  | Aluminum               | n/a       |
| Pulse XE       | E3D V6     | 300 (500 w/ upgrade) | Aluminum Copper        | 30        |

*** Notes
- Melting block material is include as it could bear on the capbility of the hot end assembly to increase or decrease the extrusion temperature at the desired rate. The density of foaming filament is often a function of extrusion temperature. Very little information is provided about the exact composition of alloys used.


** System

| Printer        | Levelling Sensor Type | Manufactuere Documentation/Support | Community | Max Bed Temp [C] | Printing Speed [mm/s] |
|----------------+-----------------------+------------------------------------+-----------+------------------+-----------------------|
| Prusa MK3S+    | Inductive             | Great                              | Large     | 120C             |                    80 |
| Ender 3 S1 Pro | Hall Effect           | Not Great                          | Large     | 110 C            |                    60 |
| Pulse XE       | Hall Effect           | Exists                             | Exists    | 115 C            |                    60 |
|                |                       |                                    |           |                  |                       |

*** Notes
- maximum printing speed depends ultimately on filament used

** Slicers
All slicers are free and open-source, both Creality and Matterhackers provide a customized version of the popular CUSA engine

** Peripherals
Potentially valuable peripherals such as enclosures and diverse material build plates are accessible to all models from the manufacturer.

* Components
- [[id:85a8da31-132f-4bb3-83bd-46749b9997bf][leveling sensors]]
- [[id:94ad490c-9dc4-4a1a-ad3e-77a0f61ca53d][extruders]]

