:PROPERTIES:
:ID:       40c5cd72-9b1a-4ed5-89a4-34802d9e247f
:END:
#+title: printing ventilation
#+filetags: :ventilation:3d:printing:

* References
[cite:@zhangChemicalCompositionToxicity2019]
[cite:@chylekParametersInfluencingEmission2021]
[cite:@zhangCharacterizationParticleEmissions2017]

* Abstract
Although there is ample research studying the emissions from extrusion type 3D printing systems, including their chemical breakdown and physical properties, there is little quantification of recommendations for mitigation of adverse health effects. Research has shown a wide array of parameters affecting the composition and physical qualities of emissions, such as filament material, printing temperature, nozzle size, and extrusion speed. Despite these factors producing varying results, all processes and parameter variations studied produce ultrafine particulate and as such it is the principal concern when considering adverse health effects. Many process variations studied produce other harmful compounds in smaller quantities such as VOCs. In reviewing OSHA standards concerning ultrafine particulate, very few national standards have codified limitations.

- what type of particles are emitted from printing
- what are the acceptable limits of these particles
- little understanding of health effects
- we will likely be using larger nozzles and higher temperatures

* Definitions

** Ultrafine Particles
Ultrafine particles (UFPs) are particulate matter of nanoscale size (less than 0.1 μm or 100 nm in diameter)

* Recommendations

** Basis
Although the exact printing parameters of the proposed research are unknown, using VarioShore filament as a baseline, it can be inferred that extrusion temperatures will exceed 230C, and a larger nozzle size will be used to achieve high material throughput. Research indicates at 235C and using a relatively standard nozzle size of 0.4mm, for prints not exceeding one hour in length and using TPU filament, ultrafine particulate emissions reached a maximum concentration of 2.7 x 10^5 particles/cm^3. The Finish OSHA has defined a maximum of 2 x 10^5 particles/cm^3. Understanding that the proposed research will likely exceed this printing temperature and nozzle size, and researching indicating both these parameters are proportional to the volume of ultrafine particulate released, it is concluded that the proposed printing processes will release ultrafine particulate exceeding recommended baselines for adverse health effects. It is also noted that in reviewing MSDS datasheets for the proposed VarioShore filament, that no recommendations are made for mitigation of adverse health effects. As such, recommendations are provided below for printing environments.

** Enclosure
Enclosing the 3D printing system significantly reduces the rate at which harmful emissions are released into the working space.

*** Risks
- large table space required for enclosure
- enclosure must remain closed during printing process to be most effective
- air extraction system failure would cause slow release of reduced emissions into working space
- enclosing the 3D printing system can cause overheating/fire if not managed appropriately

** Enclosure & Exhaust
Additionally an air extraction system reduces the potential of emissions reaching the working space significantly. This option may pose significant difficulty if there is not easy access to a dedicated air extraction system presently.

*** Risks
- extracting air from the printing enclosure can cause instability in environmental parameters throughout the printing process, potentially causing inconsistencies with print quality and print repeatability
- spot/dedicated exhaust system required
- air extraction system failure would permit slow release of reduced emissions into working space

** Enclosure & Filter
Using a filter in conjunction with an enclosure achieves significant mitigation of the release of ultrafine particles into the working space, but does not impact release of gaseous compounds such as VOCs. There are products available for mounting to most stock enclosure systems, which employ standard size HEPA or MERV filters.

*** Risks
- HEPA and/or high rated MERV filters (such as MERV 17) are not certified to filter emissions such as VOCs
- available filter products are incompatible with selected printing system
- filters need to be monitored and replaced periodically

* Conclusion
In ranked order of effectiveness and overall user comfort level the above recommendations are:
1) Enclosure & Exhaust
2) Enclosure & Filter
3) Enclosure
Using an enclosure as the sole component of an emissions mitigation system may be suitable in, infrequently occupied, well ventilated environments (exceeding 1ACH). 
